# Generated by Django 2.0.2 on 2018-03-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bornAt', models.CharField(max_length=100)),
                ('diedAt', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('publishedAt', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=400)),
                ('country', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('auther_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Auther')),
            ],
        ),
        migrations.AddField(
            model_name='auther',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Book'),
        ),
    ]
