# Generated by Django 2.0.3 on 2018-03-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='imageUrl',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AddField(
            model_name='book',
            name='imageUrl',
            field=models.CharField(default='null', max_length=400),
        ),
    ]
