# Generated by Django 2.0.3 on 2018-03-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_auto_20180306_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookauther',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookauther',
            name='Autherid',
        ),
        migrations.RemoveField(
            model_name='bookauther',
            name='Bookid',
        ),
        migrations.DeleteModel(
            name='BookAuther',
        ),
    ]
