# Generated by Django 2.0.3 on 2018-03-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20180306_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='auther',
            name='book_id',
        ),
        migrations.AddField(
            model_name='bookauther',
            name='Autherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Auther'),
        ),
        migrations.AddField(
            model_name='bookauther',
            name='Bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='bookauther',
            unique_together={('Bookid', 'Autherid')},
        ),
    ]
